version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    allow:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    allow:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
