// Generated by scripts/generate-contract-types.mjs. Do not edit by hand.
// Sources: specs/001-supervised-autonomous-loop/contracts/http-api.openapi.yaml and specs/001-supervised-autonomous-loop/contracts/execution-backend.schema.json.
// The approved schemas remain authoritative; these derivatives are non-authoritative.

export const PROJECT_STATES = ["CREATING","ACTIVE","PAUSING","PAUSED","RESUMING","STOPPING","STOPPED","CANCELLING","COMPLETED","BLOCKED","FAILED","CANCELLED"] as const;
export type ProjectState = (typeof PROJECT_STATES)[number];

export const TASK_STATES = ["PROPOSED","READY","QUEUED","RUNNING","WAITING_FOR_AGENT","WAITING_FOR_CAPACITY","WAITING_FOR_APPROVAL","BLOCKED","CLAIMED_COMPLETE","VERIFYING","VERIFIED","FAILED","CANCELLED"] as const;
export type TaskState = (typeof TASK_STATES)[number];

export const EXECUTION_STATES = ["QUEUED","STARTING","RUNNING","WAITING_FOR_APPROVAL","CHECKPOINTING","SUSPENDED","STOPPING","STOPPED","SUCCEEDED","FAILED","CANCELLED","LOST","RECONCILING"] as const;
export type ExecutionState = (typeof EXECUTION_STATES)[number];

export const PRESENCE_STATES = ["IDLE","QUEUED","THINKING_PROVIDER_CALL","USING_TOOLS","WAITING_FOR_RUNNER","WAITING_FOR_AGENT","WAITING_FOR_APPROVAL","VERIFYING","BLOCKED","COMPLETED","FAILED"] as const;
export type PresenceState = (typeof PRESENCE_STATES)[number];

export const PRESENCE_SOURCE_TYPES = ["IDENTITY","TASK","EXECUTION","TOOL_INVOCATION","APPROVAL","CAPACITY","VERIFICATION_EVALUATION"] as const;
export type PresenceSourceType = (typeof PRESENCE_SOURCE_TYPES)[number];

export const AGENT_IDENTITY_STATES = ["CREATED","ACTIVE","PAUSED","DISABLED","COMPLETED","FAILED","ARCHIVED"] as const;
export type AgentIdentityState = (typeof AGENT_IDENTITY_STATES)[number];

export const PERSONA_IDENTITY_STATES = ["ACTIVE","DISABLED","ARCHIVED"] as const;
export const SPECIALIST_IDENTITY_STATES = ["CREATED","ACTIVE","PAUSED","COMPLETED","FAILED","ARCHIVED"] as const;

export type BackendEventType = "STARTED" | "PROGRESS" | "TOOL_INTENT" | "CHECKPOINT" | "ARTIFACT" | "COMPLETED" | "FAILED" | "CANCELLED";

export interface BackendObservable {
  readonly status: string;
  readonly summary: string;
  readonly progressPercent?: number;
  readonly toolOperation?: "WRITE_APPROVED_MARKER";
  readonly actionDigest?: string;
  readonly checkpointId?: string;
  readonly artifactId?: string;
  readonly contentHash?: string;
  readonly failureCategory?: "CANCELLED" | "TIMEOUT" | "CAPABILITY_UNSUPPORTED" | "CHECKPOINT_INVALID" | "TOOL_REJECTED" | "BUDGET_EXHAUSTED" | "BACKEND_LOST";
}

export interface BackendEvent {
  readonly schemaVersion: "1.0";
  readonly messageId: string;
  readonly kind: "backend.event";
  readonly connectionId: string;
  readonly correlationId: string;
  readonly sentAt: string;
  readonly executionId: string;
  readonly modelDescriptorId: string;
  readonly modelDescriptorVersion: number;
  readonly sequence: number;
  readonly eventType: BackendEventType;
  readonly observable: BackendObservable;
  readonly usage: { readonly synthetic: true; readonly invocations: number; readonly units: number };
}
